import { existsSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { createInterface } from 'node:readline';

import { stringify } from 'yaml';

/**
 * `tripwire init` — a guided setup that asks plain-language questions and
 * writes the config for you. No YAML knowledge required.
 *
 * The config-building core is a pure function (`buildConfig`) so it is unit
 * tested; the wizard is a thin readline layer on top.
 */

export interface WizardUpstream {
  name: string;
  command: string[];
  /** "Can outside content reach you through this server?" */
  carriesOutsideContent: boolean;
}

export interface WizardGuardedTool {
  /** Tool pattern, e.g. payments__send_payment or payments__* */
  tool: string;
  /** Parameter names that must come from a trusted source. */
  protectedParams: string[];
}

export interface WizardAnswers {
  upstreams: WizardUpstream[];
  guardedTools: WizardGuardedTool[];
  requireIntent: boolean;
  /** AI double-check panel, e.g. ['anthropic/claude-sonnet-4-6']. Empty = deterministic tiers only. */
  panel: string[];
}

export const PROVIDER_KEYS: { env: string[]; model: string; label: string }[] = [
  { env: ['ANTHROPIC_API_KEY'], model: 'anthropic/claude-sonnet-4-6', label: 'Anthropic (Claude)' },
  { env: ['OPENAI_API_KEY'], model: 'openai/gpt-5.1', label: 'OpenAI (GPT)' },
  {
    env: ['GEMINI_API_KEY', 'GOOGLE_API_KEY'],
    model: 'google/gemini-2.5-pro',
    label: 'Google (Gemini)',
  },
];

/** Which AI providers have API keys available right now? */
export function detectProviders(env: NodeJS.ProcessEnv = process.env): typeof PROVIDER_KEYS {
  return PROVIDER_KEYS.filter((p) => p.env.some((e) => (env[e] ?? '') !== ''));
}

/** Build the Tripwire config object from wizard answers. Pure; unit tested. */
export function buildConfig(answers: WizardAnswers): Record<string, unknown> {
  const rules: Record<string, unknown>[] = [];

  for (const guarded of answers.guardedTools) {
    const sensitive: Record<string, { provenance: string }> = {};
    for (const param of guarded.protectedParams) {
      sensitive[param] = { provenance: 'trusted' };
    }
    rules.push({
      match: { tool: guarded.tool },
      ...(Object.keys(sensitive).length > 0 ? { sensitive_params: sensitive } : {}),
      verify: {
        tiers:
          answers.panel.length > 0
            ? ['receipts', 'provenance', 'consensus']
            : ['receipts', 'provenance'],
        ...(answers.requireIntent ? { require_intent: true } : {}),
        ...(answers.panel.length > 0
          ? {
              panel: answers.panel,
              quorum: answers.panel.length > 1 ? 'majority' : 'unanimous',
            }
          : {}),
        on_fail: 'block',
        fail_mode: 'closed',
      },
    });
  }

  // Safety net: anything a server itself marks as destructive gets the
  // deterministic tiers, even if the user never mentioned it.
  rules.push({
    match: { annotation: { destructiveHint: true } },
    verify: { tiers: ['receipts', 'provenance'], on_fail: 'block' },
  });

  return {
    upstreams: answers.upstreams.map((u) => ({
      name: u.name,
      command: u.command,
      trust: u.carriesOutsideContent ? 'untrusted' : 'trusted',
    })),
    defaults: { on_unmatched: 'pass', audit: 'all' },
    rules,
    state_dir: '.tripwire',
  };
}

export function configToYaml(answers: WizardAnswers): string {
  const header = `# Tripwire configuration — generated by \`tripwire init\`.
# Plain-language reference: docs/POLICY.md
# Re-run \`tripwire init\` any time to start over, or edit this file directly.

`;
  return header + stringify(buildConfig(answers));
}

/** The snippet a user pastes into Claude Desktop / Claude Code / any MCP host. */
export function agentSnippet(configPath: string, panel: string[]): string {
  const env: Record<string, string> = {};
  for (const provider of PROVIDER_KEYS) {
    if (panel.includes(provider.model)) env[provider.env[0]!] = '<your key here>';
  }
  return JSON.stringify(
    {
      mcpServers: {
        tripwire: {
          command: 'tripwire',
          args: ['run', '--config', resolve(configPath)],
          ...(Object.keys(env).length > 0 ? { env } : {}),
        },
      },
    },
    null,
    2,
  );
}

const VALID_NAME = /^[A-Za-z0-9][A-Za-z0-9-]*$/;

export async function runInitWizard(configPath = 'tripwire.yaml'): Promise<void> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const out = (s = ''): void => void process.stdout.write(s + '\n');

  // A buffered line reader instead of rl.question(): answers that arrive
  // while no question is pending (pasted blocks, piped input) are queued
  // rather than silently dropped.
  const pending: string[] = [];
  let waiter: ((line: string | null) => void) | null = null;
  let inputClosed = false;
  rl.on('line', (line) => {
    if (waiter !== null) {
      const resolve = waiter;
      waiter = null;
      resolve(line);
    } else {
      pending.push(line);
    }
  });
  rl.on('close', () => {
    inputClosed = true;
    if (waiter !== null) {
      const resolve = waiter;
      waiter = null;
      resolve(null);
    }
  });
  const readLine = (prompt: string): Promise<string | null> => {
    process.stdout.write(prompt);
    if (pending.length > 0) return Promise.resolve(pending.shift()!);
    if (inputClosed) return Promise.resolve(null);
    return new Promise((resolve) => {
      waiter = resolve;
    });
  };

  const ask = async (question: string, fallback?: string): Promise<string> => {
    const suffix = fallback === undefined ? '' : ` [${fallback}]`;
    const line = await readLine(`  ${question}${suffix} `);
    if (line === null) {
      throw new Error('setup ended early — input closed before all questions were answered');
    }
    const answer = line.trim();
    return answer === '' && fallback !== undefined ? fallback : answer;
  };
  const askYesNo = async (question: string, fallback: boolean): Promise<boolean> => {
    const answer = await ask(`${question} (yes/no)`, fallback ? 'yes' : 'no');
    return /^y(es)?$/i.test(answer);
  };

  try {
    out();
    out('Welcome to Tripwire setup. A few plain-language questions and');
    out("you're protected — no config files to write by hand.");
    out();

    if (existsSync(configPath)) {
      const overwrite = await askYesNo(`${configPath} already exists. Replace it?`, false);
      if (!overwrite) {
        out('  Keeping your existing config. Nothing was changed.');
        return;
      }
    }

    // ── 1. Tool servers ──────────────────────────────────────────────────
    out('STEP 1 — Your tool servers');
    out('  These are the MCP servers your AI agent currently uses (the same');
    out('  commands that are in its config today).');
    out();
    const upstreams: WizardUpstream[] = [];
    for (;;) {
      let name = await ask(
        upstreams.length === 0
          ? 'Short name for your first tool server (e.g. payments):'
          : 'Short name for another server (or press Enter to finish):',
        upstreams.length === 0 ? undefined : '',
      );
      if (name === '') {
        if (upstreams.length > 0) break;
        out('  At least one server is needed — what does your agent talk to?');
        continue;
      }
      name = name.toLowerCase().replace(/[^a-z0-9-]+/g, '-');
      if (!VALID_NAME.test(name) || name === 'tripwire') {
        out('  Please use letters, numbers, and dashes (and not "tripwire").');
        continue;
      }
      const commandLine = await ask(`Command that starts "${name}" (e.g. npx some-mcp-server):`);
      const command = commandLine.split(/\s+/).filter((s) => s !== '');
      if (command.length === 0) {
        out('  That command was empty — try again.');
        continue;
      }
      const outside = await askYesNo(
        `Can content from OUTSIDE your organization reach the agent through "${name}"?\n` +
          '    (yes for: web browsing, email, shared documents, chat — anything an\n' +
          '    outsider could write into. no for: your own database or internal API)',
        true,
      );
      upstreams.push({ name, command, carriesOutsideContent: outside });
      out(
        outside
          ? `  ✔ Added "${name}" as UNTRUSTED — values found only there can't drive dangerous actions.`
          : `  ✔ Added "${name}" as TRUSTED — it can vouch for values like account numbers.`,
      );
      out();
    }

    // ── 2. Dangerous tools ───────────────────────────────────────────────
    out();
    out('STEP 2 — The actions worth guarding');
    out('  Which tools could cause real damage if they ran with the wrong');
    out('  values? (payments, sending email, deleting things, posting publicly)');
    out();
    const guardedTools: WizardGuardedTool[] = [];
    for (;;) {
      const tool = await ask(
        guardedTools.length === 0
          ? `Tool to guard (e.g. ${upstreams[0]!.name}__send_payment, or ${upstreams[0]!.name}__* for all):`
          : 'Another tool to guard (or press Enter to finish):',
        guardedTools.length === 0 ? undefined : '',
      );
      if (tool === '') {
        if (guardedTools.length > 0) break;
        const none = await askYesNo(
          'No guarded tools yet — continue with only the automatic safety net?',
          false,
        );
        if (none) break;
        continue;
      }
      const paramsRaw = await ask(
        `Which inputs of "${tool}" must come from a trusted source?\n` +
          '    (comma-separated, e.g. recipient, amount — or Enter for none)',
        '',
      );
      const protectedParams = paramsRaw
        .split(',')
        .map((p) => p.trim())
        .filter((p) => p !== '');
      guardedTools.push({ tool, protectedParams });
      out(`  ✔ "${tool}" will be verified before it runs.`);
      out();
    }

    // ── 3. Intent + AI verification ──────────────────────────────────────
    out();
    out('STEP 3 — Extra protection');
    const requireIntent = await askYesNo(
      'Require the agent to state its goal before dangerous actions?\n' +
        '    (recommended — its later actions are checked against that goal)',
      true,
    );

    const available = detectProviders();
    let panel: string[] = [];
    if (available.length > 0) {
      out();
      out(`  Found API keys for: ${available.map((p) => p.label).join(', ')}.`);
      const useAi = await askYesNo(
        'Add an AI double-check on guarded actions using those keys?\n' +
          "    (independent models review each dangerous call; if they can't be\n" +
          '    reached, the action is blocked rather than allowed through)',
        true,
      );
      if (useAi) panel = available.map((p) => p.model);
    } else {
      out();
      out('  No AI provider API keys found in this terminal, so the AI');
      out('  double-check is off for now. The deterministic protections (which');
      out('  stop the headline attacks) are always on. To add AI review later,');
      out('  set ANTHROPIC_API_KEY / OPENAI_API_KEY / GEMINI_API_KEY and re-run');
      out('  tripwire init.');
    }

    // ── Write everything ─────────────────────────────────────────────────
    const answers: WizardAnswers = { upstreams, guardedTools, requireIntent, panel };
    writeFileSync(configPath, configToYaml(answers));
    const snippetPath = join(dirname(resolve(configPath)), 'tripwire-agent-config.json');
    writeFileSync(snippetPath, agentSnippet(configPath, panel) + '\n');

    out();
    out('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    out(`  ✔ Wrote ${configPath} (your protection rules)`);
    out(`  ✔ Wrote ${snippetPath} (paste this into your agent's MCP settings,`);
    out('    replacing the servers it lists today — Tripwire now sits in front');
    out('    of them)');
    out();
    out('  Next steps:');
    out(`    1. tripwire check --config ${configPath}     (make sure everything works)`);
    out(`    2. Update your agent's MCP settings with ${snippetPath}`);
    out('    3. Use your agent normally — dangerous calls are now verified.');
    out();
    out('  Any time later: tripwire logs <session folder> shows, in plain');
    out('  English, everything the agent did and what was blocked.');
    out('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  } finally {
    rl.close();
  }
}
